### ISSUE TITLE
Make the processor buildable as standalone project

### ISSUE THREAD

**Issue by adam-stanek** [LodestoneHQ/lodestone#111]
The project is currently closed to contributors because there is no easy way how to build its parts without being owner of the organization. Processor image is built from artifacts which are attached to the project release. There is no way anybody can build Docker image like that.

Each application should instead be buildable as a separate thing and the lodestone project should serve only as orchestration of separately built images from separate repos (ie. to hold docker-compose file, helm chart, documentation, ...). With this setup you will allow people to fork individual repos and build their own images for testing of contributed features.

I have already created PR with prepared Dockerfiles: https://github.com/LodestoneHQ/lodestone-processor/pull/35

**Comment by dskaggs** [comment]
Fixed in https://github.com/LodestoneHQ/lodestone-processor/pull/35
