### ISSUE TITLE
Update docker-compose files

### ISSUE THREAD

**Issue by dskaggs** [LodestoneHQ/lodestone#113]
* Update docker-compose.yml to use new Docker processor images (see example provided by @adam-stanek here: https://github.com/LodestoneHQ/lodestone-processor/pull/35#issuecomment-772790120 )
* Remove docker-compose.dev
* Update README on how to launch the project and how to do UI dev

**Comment by adam-stanek** [comment]
I noticed one more thing while testing it out. Since the new document image is based on scratch, there is no `/tmp` directory. 

We might want to add:

```docker
RUN mkdir /tmp
```
to the `Dockerfile.document`

or mount it here as volume with something like:

```yaml
volumes:
- ./data/document-tmp:/tmp
```

for the `document_processor`

**Comment by dskaggs** [comment]
> RUN mkdir /tmp

Confirmed that the document processor errors out without the `/tmp` directory being present. I've added that command to the Dockerfile.document
