### ISSUE TITLE
Move `/web` into a separate repository?

### ISSUE THREAD

**Issue by dskaggs** [LodestoneHQ/lodestone#124]
Should we look at moving the web frontend and backend out into a separate repo? This would allow us to use the main `lodestone` repo be the one that people can clone and run `docker-compose up` against and collect all issues for the project there.

Possibly move those into `lodesteone-ui`?

Thoughts?

cc: @adam-stanek

**Comment by adam-stanek** [comment]
Yeah, I think it is a good idea 👍

**Comment by adam-stanek** [comment]
While we are at it we should also check the actual build. This is triggers a lot of red flags: https://github.com/LodestoneHQ/lodestone-ui/blob/main/rootfs/etc/services.d/frontend/run#L15

The FE should be built statically. We can then serve the static files by BE. It is already based on `express`. It is matter of 1 line of code and we can simplify the whole thing.

**Comment by dskaggs** [comment]
Agreed. For now I wanted to try to limit the scope of changes to get the repos separated so I left the existing build process alone. The PR to extract the different services from this repo is already pretty large. I'd rather have a separate ticket for work to modernize the build process.
